### ISSUE TITLE
How to catch promise rejections?

### ISSUE THREAD

**Issue by gzurbach** [teddyzeenny/ember-mocha-adapter#34]
Hi everyone,

I'm trying to write an acceptance test where a user would submit and invalid form. I'm using [ember-cli-mirage](http://www.ember-cli-mirage.com).

Here is the test:
```javascript
it('shows an error message', function(done) {
  server.create('user');
  server.put('user/1', { message: 'Invalid data' }, 400);

  visit('/my-account');
    
  Ember.run(function() {
    click('.save-button');
  });
    
  andThen(function() {
    assert.equal(currentRouteName(), 'my-account');
    assert.equal(find('.alert-error').length, 1);
    done();
  });
});
```
And here is the save method:
```
actions: {
  saveUser(user) {
    var promise = user.save();

    promise.then(() => {
      this.alerts.success('User saved.');
      this.transitionTo('index');
    });

    promise.catch(()=> {
      this.alerts.error('Cannot save.');
    });
  }
}
```
My test keeps failing with the message `Error: Adapter operation failed`. I've been told to wrap the click inside `Ember.run` but it doesn't change much. The test passes but the afterEach hooks fails with the same error message.

Since I'm catching the error in the `saveUser` method, why is my test failing? Any idea on how to prevent that?

**Comment by teddyzeenny** [comment]
Two unrelated points:

- You can remove `Ember.run` around `click`. You don't need it.
- You can remove `done`. You don't need it.

As for the error it is strange since you are obviously catching the promise failure. Is it possible it's a different promise that's causing the failure? Which Ember / ED versions are you on?

**Comment by gzurbach** [comment]
Thanks for taking the time to answer! I actually just found a solution:
```javascript
beforeEach(function() {
  application = startApp();
  Ember.RSVP.off('error');
});

afterEach(function() {
  Ember.run(application, 'destroy');
  Ember.RSVP.on('error');
});
```
Turning on and off the RSVP global error handler completely fixed my issue. I need to be careful though because other exceptions could be swallowed too and therefore tests that should be failing will now pass. I decided to isolate failure tests into their own `describe` to make sure my "hack" won't affect other tests.

I also removed the `done` and `Ember.run` since they were useless.

Thanks again!

**Comment by seawatts** [comment]
You're welcome :+1:

**Comment by gzurbach** [comment]
Hehe yes, thanks a lot @seawatts for your help :)

**Comment by teddyzeenny** [comment]
I don't think `Ember.RSVP.on('error');` will bring the listeners back. `on('error')` takes a callback: `RSVP.on('error', function() { });` So the previous event handlers will remain cancelled and `on('error')` probably does nothing - I'm even a bit surprised it doesn't throw an error.

It is true that RSVP's error handler is what was triggering the test failure, however `on('error')` shouldn't have been firing if you're catching the promise. So I believe that something is still off.

**Comment by gzurbach** [comment]
@teddyzeenny you are correct `RSVP.on('error')` doesn't do anything. I really have a hard time understanding how promise rejections are handled in Ember, this is not the first time I'm having weird issues like that. I'm gonna try to set back to original error handler after my test and see if it works... it's kinda of a hack but I don't have a better idea for now.

**Comment by seawatts** [comment]
So what is actually happening in ember data is if the ajax request fails it rejects the promise. See https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest-adapter.js#L827

The Adapter error is where the `Error: Adapter operation failed` text gets set. https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/errors.js#L9

So because you are not explicitly handling the rejection of the promise in your code it bubbles up and is an uncaught promise exception which will fail your test. By turning of Ember catching RSVP errors this prevents the exception from being caught by the default behaviour of `RSVP.on('error')` which will fail the test. See: https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/packages/ember-runtime/lib/ext/rsvp.js#L65

**Comment by gzurbach** [comment]
I'm confused. I thought that:
```
    promise.catch(()=> {
      this.alerts.error('Cannot save.');
    });
```
would handle the rejection?

**Comment by seawatts** [comment]
Which version of ember data are you on?

**Comment by seawatts** [comment]
Also are you rethrowing the error in your catch handler?

**Comment by gzurbach** [comment]
```
DEBUG: Ember      : 1.13.6
DEBUG: Ember Data : 1.13.7
```
I am not retrowing the error.

**Comment by gzurbach** [comment]
OK so I have no idea what's going on but I need to move on so I ended up doing this:
```javascript
it('will not blow up this time', function() {
  Ember.RSVP.off('error');
  server.put('user/1', { message: 'Invalid data' }, 400);
  // rest of the test
});
```
Then I added a `reset-test.js` file at the root of the `test` directory:
```javascript
afterEach(function () {
  Ember.RSVP.on('error', function(error) {
    throw error;
  });
});
```
That global reset guarantees that other tests won't be affected by my hack. I also think this issue is related to https://github.com/switchfly/ember-mocha/issues/51. Not sure though.

**Comment by seawatts** [comment]
Alright, seems legit for now.
